import * as THREE from 'three';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';

const WIDTH=276,HEIGHT=182,SOURCE_WIDTH=340,SOURCE_HEIGHT=285,CROP_X=32,CROP_Y=97,VERSION='tighter-hitbox-v14-movie-dance';
// Rest-pose shoulder bisector of the MovieGoodbye forearms Limb1/Limb2.
// Blender XY (x right, y away) -> Three XZ (x right, z=-y): local front=(0.27105,0.37307), yaw=+0.62814 rad.
const CANONICAL_FACE_LOCAL_YAW=0.62814, VIEWER_PIVOT_YAW=-CANONICAL_FACE_LOCAL_YAW, VIEW_TURN_MS=360;
const canvas=document.getElementById('rocky-canvas');
const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,preserveDrawingBuffer:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.35)); renderer.setSize(WIDTH,HEIGHT,false); renderer.setClearColor(0,0);
renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.18; renderer.shadowMap.enabled=false;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(27,SOURCE_WIDTH/SOURCE_HEIGHT,.05,50); camera.position.set(0,2.55,8.4); camera.lookAt(0,1.35,0); camera.setViewOffset(SOURCE_WIDTH,SOURCE_HEIGHT,CROP_X,CROP_Y,WIDTH,HEIGHT);
scene.add(new THREE.HemisphereLight(0xc9c9c4,0x211913,1.55));
const key=new THREE.DirectionalLight(0xffd7ad,3.9); key.position.set(-4.8,7.6,5.6); scene.add(key);
const fill=new THREE.DirectionalLight(0x91abb3,1.10); fill.position.set(4.8,2.8,4.6); scene.add(fill);
const rim=new THREE.DirectionalLight(0xb8cbd0,2.20); rim.position.set(3.4,5.4,-5.8); scene.add(rim);
const bounce=new THREE.PointLight(0xa16849,.55,8); bounce.position.set(-2.4,.28,2.5); scene.add(bounce);
const rocky=new THREE.Group(); rocky.position.y=-.06; scene.add(rocky);
// This pivot is deliberately outside the animated GLB: root animation can never overwrite facing.
const facingPivot=new THREE.Group(),modelHolder=new THREE.Group(); rocky.add(facingPivot); facingPivot.add(modelHolder);
function contactShadow(){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d'),g=x.createRadialGradient(64,64,4,64,64,62);g.addColorStop(0,'rgba(17,13,10,.12)');g.addColorStop(.34,'rgba(17,13,10,.05)');g.addColorStop(.72,'rgba(17,13,10,.01)');g.addColorStop(1,'rgba(17,13,10,0)');x.fillStyle=g;x.fillRect(0,0,128,128);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const m=new THREE.Mesh(new THREE.PlaneGeometry(1.8,0.8),new THREE.MeshBasicMaterial({map:t,transparent:true,depthWrite:false,opacity:.15}));m.rotation.x=-Math.PI/2;m.position.set(0,.012,.12);m.renderOrder=-1;return m} rocky.add(contactShadow());
const materialCache=new Map();
const clamp01=x=>Math.max(0,Math.min(1,x)),fract=x=>x-Math.floor(x);
function segmentInk(px,py,ax,ay,bx,by,w){const vx=bx-ax,vy=by-ay,wx=px-ax,wy=py-ay,h=clamp01((wx*vx+wy*vy)/(vx*vx+vy*vy));return Math.hypot(wx-vx*h,wy-vy*h)<w?1:0}
function bakeStoneColors(geometry,name=''){
  const p=geometry.attributes.position,n=geometry.attributes.normal,collar=/Collar/i.test(name),torso=/Torso/i.test(name),marked=/Limb1_Lower/i.test(name),out=new Float32Array(p.count*3);
  const umber=new THREE.Color(0x3d2d22),basalt=new THREE.Color(collar?0x514a43:torso?0x67584a:0x5e5145),cool=new THREE.Color(0x747975),worn=new THREE.Color(0x897667),ink=new THREE.Color(0x403b35),c=new THREE.Color();
  for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i),nx=n?.getX(i)||0,ny=n?.getY(i)||1,nz=n?.getZ(i)||0;
    const macro=.5+.24*Math.sin(x*18.7+y*13.1+z*15.3)+.14*Math.sin(x*39.1-y*27.3+z*31.7)+.07*Math.sin(x*83.3+y*61.1-z*71.9),ridge=Math.pow(clamp01((nx*-.32+ny*.82+nz*.27)*.5+.5),2.2),seam=Math.abs(fract((y+macro*.035)*9.1)-.5)<.045?1:0,grain=fract(Math.sin((x*93.1+y*117.7+z*81.9)*12.9898)*43758.5453)>.975?1:0;
    c.copy(umber).lerp(basalt,clamp01(.18+macro*.76)).lerp(cool,.13*ridge).lerp(worn,.075*clamp01((macro-.66)*3.4));c.multiplyScalar(1-.075*seam-.045*grain);
    if(marked){const qx=(x-.061)/.20,qy=(y-.158)/.44,inner=clamp01((.05-(z-1.01)/.47)/.27),glyph=Math.max(segmentInk(qx,qy,-.42,-.25,.34,-.05,.045),segmentInk(qx,qy,.34,-.05,-.18,.18,.045),segmentInk(qx,qy,-.18,.18,.30,.34,.04));if(glyph&&inner>.25)c.lerp(ink,.24*inner)}
    out[i*3]=c.r;out[i*3+1]=c.g;out[i*3+2]=c.b;
  }
  geometry.setAttribute('color',new THREE.BufferAttribute(out,3));
}
function stone(name='',geometry){const collar=/Collar/i.test(name),torso=/Torso/i.test(name),marked=/Limb1_Lower/i.test(name),family=marked?'marked':collar?'collar':torso?'torso':'limb';bakeStoneColors(geometry,name);if(materialCache.has(family))return materialCache.get(family);const mat=new THREE.MeshStandardMaterial({color:0xffffff,vertexColors:true,roughness:collar?.92:torso?.88:.90,metalness:0,envMapIntensity:.10});mat.name=`Basalt_${family}`;materialCache.set(family,mat);return mat}
const MAP={idle:'CuteIdle',cuteidle:'CuteIdle',walk:'Walk',goodbye:'MovieGoodbye',moviegoodbye:'MovieGoodbye',knock:'Knock',macarena:'MirrorDance',mirror:'MirrorDance',mirrordance:'MirrorDance',jazz:'MirrorDance',happy:'MirrorDance',wave:'MirrorDance',tilt:'CuteIdle'};
const TARGET={Walk:1.6,MovieGoodbye:2.5,Knock:3,MirrorDance:2.333333},FALLBACK={CuteIdle:900,Walk:1600,MovieGoodbye:2500,Knock:3000,MirrorDance:2334};
let mixer,model,idleAction,currentAction,currentName='',queuedName=null,viewActionTimer=null,faceReleaseTimer=null;const actions=new Map(),clock=new THREE.Clock();
const cursorTarget={yaw:VIEWER_PIVOT_YAW,pitch:0,roll:0},cursorPose={yaw:VIEWER_PIVOT_YAW,pitch:0,roll:0};
let faceMode='cursor';
const normalize=n=>MAP[String(n||'idle').toLowerCase()]||'CuteIdle';
function durationMs(n){const c=normalize(n);return Math.round((TARGET[c]||actions.get(c)?.getClip().duration||FALLBACK[c]/1000)*1000)}
function fadeIdle(fade=.36){if(!idleAction)return;if(currentAction&&currentAction!==idleAction)currentAction.fadeOut(fade);idleAction.enabled=true;idleAction.reset().setLoop(THREE.LoopRepeat,Infinity).setEffectiveTimeScale(1).setEffectiveWeight(1).fadeIn(fade).play();currentAction=idleAction;currentName='CuteIdle';window.__rockyLive.activeClip=currentName}
function perform(requested){const clipName=normalize(requested);if(!mixer||!actions.size){queuedName=requested;return durationMs(requested)}if(clipName==='CuteIdle'){fadeIdle();return durationMs(clipName)}const next=actions.get(clipName)||idleAction;if(!next||next===idleAction){fadeIdle();return durationMs('idle')}const fade=.28;if(currentAction&&currentAction!==next)currentAction.fadeOut(fade);next.stop();next.enabled=true;const target=TARGET[clipName]||next.getClip().duration;next.reset().setLoop(THREE.LoopOnce,1).setEffectiveTimeScale(next.getClip().duration/target).setEffectiveWeight(1);next.clampWhenFinished=false;next.fadeIn(fade).play();currentAction=next;currentName=clipName;window.__rockyLive.activeClip=clipName;window.__rockyLive.startedAt=performance.now();return Math.round(target*1000)}
function performFacingViewer(requested){
  const actionMs=durationMs(requested);
  clearTimeout(viewActionTimer); clearTimeout(faceReleaseTimer);
  faceMode='viewer'; window.__rockyLive.faceMode='viewer-turn'; window.__rockyLive.facingTargetYaw=VIEWER_PIVOT_YAW; window.__rockyLive.clickAction=requested;
  // Hold idle while the non-animated outer pivot turns, then start the clip.
  fadeIdle(.18);
  viewActionTimer=setTimeout(()=>{window.__rockyLive.faceMode='viewer-hold';perform(requested)},VIEW_TURN_MS);
  faceReleaseTimer=setTimeout(()=>{faceMode='cursor';window.__rockyLive.faceMode='cursor'},VIEW_TURN_MS+actionMs+120);
  return VIEW_TURN_MS+actionMs+120;
}
window.__rockyLive={version:VERSION,loaded:false,activeClip:'',clips:[],errors:[],frames:0,fps:0,faceMode:'cursor',canonicalFaceLocalYaw:CANONICAL_FACE_LOCAL_YAW,viewerPivotYaw:VIEWER_PIVOT_YAW,box:{width:WIDTH,height:HEIGHT},crop:{sourceWidth:SOURCE_WIDTH,sourceHeight:SOURCE_HEIGHT,x:CROP_X,y:CROP_Y}};
let resolveReady,rejectReady;const ready=new Promise((resolve,reject)=>{resolveReady=resolve;rejectReady=reject});
function interactionAlpha(clientX,clientY,radius=7){if(!Number.isFinite(clientX)||!Number.isFinite(clientY)||clientX<0||clientY<0||clientX>=WIDTH||clientY>=HEIGHT)return {maxAlpha:0,strongPixels:0,radius};const gl=renderer.getContext(),scaleX=gl.drawingBufferWidth/WIDTH,scaleY=gl.drawingBufferHeight/HEIGHT,cx=Math.floor(clientX*scaleX),cy=Math.floor((HEIGHT-clientY)*scaleY),rx=Math.max(1,Math.ceil(radius*scaleX)),ry=Math.max(1,Math.ceil(radius*scaleY)),left=Math.max(0,cx-rx),bottom=Math.max(0,cy-ry),right=Math.min(gl.drawingBufferWidth,cx+rx+1),top=Math.min(gl.drawingBufferHeight,cy+ry+1),pixels=new Uint8Array((right-left)*(top-bottom)*4);gl.readPixels(left,bottom,right-left,top-bottom,gl.RGBA,gl.UNSIGNED_BYTE,pixels);let maxAlpha=0,strongPixels=0;for(let i=3;i<pixels.length;i+=4){const alpha=pixels[i];if(alpha>maxAlpha)maxAlpha=alpha;if(alpha>=8)strongPixels++}return {maxAlpha,strongPixels,radius}}
window.RockyScene={ready,get isReady(){return window.__rockyLive.loaded},walk(duration=1600){TARGET.Walk=Math.max(.6,duration/1000);return perform('walk')},perform,performFacingViewer,faceCursor(dx=0,dy=0){const desiredWorldYaw=THREE.MathUtils.clamp(Math.atan2(dx,480),-.50,.50);cursorTarget.yaw=VIEWER_PIVOT_YAW+desiredWorldYaw;window.__rockyLive.facingTargetYaw=cursorTarget.yaw;cursorTarget.pitch=THREE.MathUtils.clamp(Math.atan2(-dy,650)*.24,-.11,.11);cursorTarget.roll=THREE.MathUtils.clamp(-dx/4800,-.055,.055)},interactionAlpha};
function measureAlpha(thresholds=[1,4,8,16,24,40,64]){const gl=renderer.getContext(),width=gl.drawingBufferWidth,height=gl.drawingBufferHeight,pixels=new Uint8Array(width*height*4),stats=thresholds.map(threshold=>({threshold,minX:width,minY:height,maxX:-1,maxY:-1,count:0}));gl.readPixels(0,0,width,height,gl.RGBA,gl.UNSIGNED_BYTE,pixels);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const alpha=pixels[(y*width+x)*4+3];if(!alpha)continue;for(const stat of stats){if(alpha<stat.threshold)continue;stat.count++;if(x<stat.minX)stat.minX=x;if(x>stat.maxX)stat.maxX=x;if(y<stat.minY)stat.minY=y;if(y>stat.maxY)stat.maxY=y}}const scaleX=width/WIDTH,scaleY=height/HEIGHT;return {buffer:{width,height},css:{width:WIDTH,height:HEIGHT},bounds:Object.fromEntries(stats.map(stat=>[stat.threshold,stat.count?{left:stat.minX/scaleX,top:(height-1-stat.maxY)/scaleY,right:(stat.maxX+1)/scaleX,bottom:(height-stat.minY)/scaleY,width:(stat.maxX+1-stat.minX)/scaleX,height:(stat.maxY+1-stat.minY)/scaleY,count:stat.count}:null]))}}
// Deterministic, synchronous render sampling used by the bounds/interaction verification tool.
window.__rockyTest={fastAlpha(){if(!model)return false;const alphaMaterial=new THREE.MeshBasicMaterial({color:0xffffff});model.traverse(node=>{if(!node.isMesh)return;node.userData.rockyVisualMaterial=node.material;node.material=alphaMaterial});return true},restoreVisual(){model?.traverse(node=>{if(node.isMesh&&node.userData.rockyVisualMaterial){node.material=node.userData.rockyVisualMaterial;delete node.userData.rockyVisualMaterial}})},frame(requested='idle',phase=0,yawOffset=0,pitch=0,roll=0){if(!mixer)return null;const clipName=normalize(requested),action=actions.get(clipName)||idleAction,targetYaw=VIEWER_PIVOT_YAW+yawOffset;mixer.stopAllAction();action.reset().setLoop(THREE.LoopOnce,1).setEffectiveWeight(1).play();mixer.update(0);action.paused=true;action.time=THREE.MathUtils.clamp(phase,0,.999999)*action.getClip().duration;mixer.update(0);cursorTarget.yaw=cursorPose.yaw=targetYaw;cursorTarget.pitch=cursorPose.pitch=pitch;cursorTarget.roll=cursorPose.roll=roll;facingPivot.rotation.set(pitch,targetYaw,roll);renderer.render(scene,camera);return {clip:clipName,phase,yawOffset,pitch,roll,...measureAlpha()}}};
new GLTFLoader().load(`assets/rocky-full-rig-multi-action-final-v2d.glb?v=${VERSION}`,gltf=>{try{model=gltf.scene;model.traverse(n=>{if(!n.isMesh)return;n.material=stone(n.name||n.parent?.name||'stone',n.geometry);n.castShadow=n.receiveShadow=false;n.frustumCulled=true});model.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),scale=3.25/Math.max(size.x,size.y,size.z);model.scale.setScalar(scale);model.position.set(-center.x*scale,-box.min.y*scale,-center.z*scale);modelHolder.add(model);mixer=new THREE.AnimationMixer(model);gltf.animations.forEach(c=>actions.set(c.name,mixer.clipAction(c)));idleAction=actions.get('CuteIdle');const required=['CuteIdle','Walk','MovieGoodbye','Knock','MirrorDance'],missing=required.filter(n=>!actions.has(n));if(missing.length)throw new Error(`Rocky rig is missing: ${missing.join(', ')}`);mixer.addEventListener('finished',e=>{if(e.action===currentAction&&e.action!==idleAction)fadeIdle(.4)});fadeIdle(0);document.body.classList.add('model-ready');window.__rockyLive.loaded=true;window.__rockyLive.clips=gltf.animations.map(c=>({name:c.name,duration:c.duration}));if(queuedName){const q=queuedName;queuedName=null;perform(q)}resolveReady(window.RockyScene)}catch(error){fail(error)}},undefined,fail);
function fail(error){console.error('Rocky GLB failed to load',error);document.getElementById('hint').textContent='Rocky model could not load';window.__rockyLive.errors.push(error?.message||String(error));rejectReady(error)}
let previous=performance.now(),fpsStart=previous,fpsFrames=0;renderer.setAnimationLoop(now=>{const delta=Math.min(clock.getDelta(),.05);if(mixer)mixer.update(delta);const dt=Math.min(.05,(now-previous)/1000||0);previous=now;const follow=1-Math.exp(-dt*(faceMode==='viewer'?10.5:6.2));const targetYaw=faceMode==='viewer'?VIEWER_PIVOT_YAW:cursorTarget.yaw,targetPitch=faceMode==='viewer'?0:cursorTarget.pitch,targetRoll=faceMode==='viewer'?0:cursorTarget.roll;cursorPose.yaw=THREE.MathUtils.lerp(cursorPose.yaw,targetYaw,follow);cursorPose.pitch=THREE.MathUtils.lerp(cursorPose.pitch,targetPitch,follow);cursorPose.roll=THREE.MathUtils.lerp(cursorPose.roll,targetRoll,follow);facingPivot.rotation.set(cursorPose.pitch,cursorPose.yaw,cursorPose.roll);window.__rockyLive.facingYaw=cursorPose.yaw;renderer.render(scene,camera);if(window.__rockyLive.loaded&&!document.body.classList.contains('rocky-visible')){try{const gl=renderer.getContext(),pixels=new Uint8Array(WIDTH*HEIGHT*4);gl.readPixels(0,0,WIDTH,HEIGHT,gl.RGBA,gl.UNSIGNED_BYTE,pixels);let opaque=0;for(let i=3;i<pixels.length;i+=4)if(pixels[i]>24&&++opaque>900)break;if(opaque>900){document.body.classList.add('rocky-visible');window.__rockyLive.visiblePixels=true}}catch(e){window.__rockyLive.errors.push('visibility check: '+e.message)}}fpsFrames++;window.__rockyLive.frames++;if(now-fpsStart>=1000){window.__rockyLive.fps=Math.round(fpsFrames*1000/(now-fpsStart));fpsFrames=0;fpsStart=now}});
